### ISSUE TITLE
Commons Gallery Online Catalog

### ISSUE THREAD

**Issue by damg70** [digiah/2do#176] opened 2016-01-29 21:28 UTC
This is the inaugrual issue...
1. Brandon Ng has set up his github account
2. Has met with David Goldberg to discuss strategy
3. Will be meeting soon

**Comment by rcrath** [comment] 2016-11-14 07:08
duplicate of #167 ?  please consolidate.

**Comment by rcrath** [comment] 2017-02-03 04:50
@damg70 update on this? wondering if this can be combined with [collective access project](#190)?

**Comment by rcrath** [comment] 2017-02-03 04:53
@damg70 I accidentally deleted Brandon from the team...sent a new invite to @brandonng, who I think is the wrong person.  Could you get him signed back up?  Sorry B^}

**Comment by rcrath** [comment] 2017-02-03 04:59
closing # 167.

**Comment by damg70** [comment] 2017-02-06 19:36
Epitaph: Brandon Ng is no longer with the university.

**Closed as completed** 2017-09-18 05:23 UTC
Labels: discuss, Commons Gallery Catalog
